repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v17.0.6'
    hooks:
    - id: clang-format
      exclude: '.*\.(json|java|js|m|mm|proto)'
  - repo: https://github.com/cpplint/cpplint
    rev: '1.6.1'
    hooks:
    - id: cpplint